function main(args as object) as object
    return roca(args).describe("csswg: 8.2 Axis Alignment: the justify-content property", sub()
        m.it("flexbox | justify-content: space-between", sub()
            args = {
                width: 480,
                height: 128,
                justifyContent: "spaceBetween"
            }
            boundingRect = { x: 0, y: 0, width: 128, height: 128 }
            sgf = new SGFlexModel([boundingRect, boundingRect, boundingRect], args)
            expected = [
                { childIndex: 1, x: 176, y: 0 },
                { childIndex: 2, x: 352, y: 0 }
            ]
            actual = sgf.getTranslations()
            m.assert.equal(FormatJson(actual), FormatJson(expected), "fail")
        end sub)

        m.it("flexbox | justify-content: space-between | single item", sub()
            args = {
                width: 480,
                height: 128,
                justifyContent: "spaceBetween"
            }
            boundingRect = { x: 0, y: 0, width: 128, height: 128 }
            sgf = new SGFlexModel([boundingRect], args)
            expected = []
            actual = sgf.getTranslations()
            m.assert.equal(FormatJson(actual), FormatJson(expected), "fail")
        end sub)
    end sub)
end function
